import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]

[font]
size = 14.0
normal = {family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular"}

[window]
option_as_alt = "OnlyLeft"
opacity = 0.95
